### ISSUE TITLE
Problem with resolver module not able to resolve rn exports

### ISSUE THREAD

**Issue by ajp8164** [psycheangel/deprecated-with-module-resolver#4]
Thanks for this great solution.. 

I've set up this solution and with the 'testing' log output I can see  that the resolver is being called correctly. The problem I'm having is that ```import * as StandardModule from 'react-native';``` results in StandardModule being set to ```{"default": {}}```. My project is setup for typescript so the import is actually pointing at ```@types/react-native``` which is correctly installed. Below is the error I get.  I guess I expect that StandardModule would show content on console log(?)

What should I be  looking at to solve this?

```
TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[5], "/Users/.../resolvers/react-native").StyleSheet.create')
```

babel.config.js
```
// eslint-disable-next-line @typescript-eslint/no-var-requires
var path = require('path');

module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        root: ['.'],
        alias: {
          components: './components/',
          lib: './lib/',
          state: './state/',
          styles: './styles/',
        },
        // See https://github.com/psycheangel/deprecated-with-module-resolver
        resolvePath(sourcePath, currentFile, _opts) {
          if (
            sourcePath === 'react-native' &&
            currentFile.includes('node_modules\\react-native\\') === false &&
            currentFile.includes('resolvers\\react-native\\') === false
          ) {
            console.log('testing', sourcePath, currentFile);
            return path.resolve(__dirname, 'resolvers/react-native');
          }
          // macos/linux paths
          // if(sourcePath === 'react-native' && currentFile.includes("node_modules/react-native/") === false && currentFile.includes('resolver/react-native/') === false){
          // console.log('testing',sourcePath, currentFile)
          // return  path.resolve(__dirname, 'resolver/react-native');
          // }
          /**
           * The `opts` argument is the options object that is passed through the Babel config.
           * opts = {
           *   extensions: [".js"],
           *   resolvePath: ...,
           * }
           */
          return undefined;
        },
      },
    ],
    [
      'babel-plugin-inline-import',
      {
        extensions: ['.svg'],
      },
    ],
    'react-native-reanimated/plugin',
    'module:react-native-dotenv',
  ],
};
```

tsconfig.json
```
// prettier-ignore
{
  "extends": "@tsconfig/react-native/tsconfig.json",
  "compilerOptions": {
    "allowJs": true,
    "alwaysStrict": true,
    "baseUrl": ".",
    "paths": {
      "components": ["./components/*", "./components/"],
      "lib": ["./lib/*", "./lib"],
      "state": ["./state/*", "./state"],
      "types": ["./styles/*", "./styles/"],
    },
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "lib": [
      "es2017"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "noEmit": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    //"target": "esnext"
  },
  "exclude": [
    "node_modules",
    "e2e"
  ],
  "include": [
    "**/*.ts",
    "**/*.tsx",
    "**/*.js",
    "**/*.jsx",
    "**/*.svg",
    "**/*.png"
  ]
}
```

**Comment by psycheangel** [comment]
Hi,

I already tested using typescript CRA (create react application)
`npx react-native init AwesomeTSProject --template react-native-template-typescript`

seems like there is no broken resolve to babel-plugin-module-resolver and no circular dependency issue.

can you check whether there is a circular resolve issue using the printed log from module-resolver
transform[stdout]:

something like resolver pointing to self js file 
transform[stdout]: testing react-native C:\testfile\AwesomeTSProject\resolver\react-native.js

also, the js file should be in directory \resolver\react-native
\resolver\react-native\index.js

or you could change 
return path.resolve(__dirname, 'resolvers/react-native');

to 
return path.resolve(__dirname, 'resolvers/react-native.js');

**Comment by ajp8164** [comment]
Thanks for the quick reply!

I changed the path.resolve to add ```.js```. Didn't resolve the issue.

I do see messages for circular dependency.

During resolution:
```testing react-native /Users/Andy/Development/flowency/excitepay-app-v2/resolvers/react-native.js```

When app starts to run:
```Require cycle: resolvers/react-native.js -> resolvers/react-native.js```

**Comment by psycheangel** [comment]
I’m glad it worked out
